#!/usr/bin/env bash

dir=$HOME/.config/yadm/bootstrap_scripts

sudo apt-get install \
    curl \
    zsh

if [ "$SHELL" != $(which zsh) ]
then
    chsh -s $(which zsh)
fi

if [ ! -d "$HOME/.zplug" ]
then
    # zplug installer
    curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
    echo 'zplug install' >> todo.log
fi

git config --global user.name qxxxb
git config --global user.email "46016483+qxxxb@users.noreply.github.com"
git config --global core.excludesFile "$HOME/.gitignore_global"

if [ ! -d "$HOME/.local/kitty.app/" ]
then
    sh $dir/install_kitty.sh
fi

sh $dir/install_fonts.sh
sh $dir/install_python.sh
sh $dir/root_configs.sh

sudo apt-get install \
    neovim \
    ripgrep \
    i3 \
    i3blocks \
    rofi \
    compton \
    nemo \
    xsel \
    light \
    firefox \
    yaru-theme-gtk \
    yaru-theme-icon \
    lxappearance \
    eog \
    feh \
    htop \
    neofetch

sudo apt-get autopurge

echo 'Done, check `todo.log` to finish.'
