#!/usr/bin/env bash

dir=$HOME/.config/yadm/bootstrap_scripts

if dpkg-query -l gnome-desktop3 |& grep -q 'no packages found'; then
    # fart
    echo 'GNOME already uninstalled'
else
    sh $dir/remove_gnome.sh
fi

sudo apt-get install \
    curl \
    zsh \
    ripgrep \
    i3 \
    i3blocks \
    rofi \
    compton \
    nemo \
    xsel \
    firefox \
    yaru-theme-gtk \
    yaru-theme-icon \
    lxappearance \
    eog \
    feh

if [ "$SHELL" != $(which zsh) ]
then
    chsh -s $(which zsh)
fi

if [ ! -d "$HOME/.zplug" ]
then
    # zplug installer
    curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
    zplug install
fi

git config --global user.name qxxxb
git config --global user.email "46016483+qxxxb@users.noreply.github.com"
git config --global core.excludesFile "$HOME/.gitignore_global"

if [ ! -d "$HOME/.local/kitty.app/" ]
then
    sh $dir/install_kitty.sh
fi

sh $dir/install_fonts.sh
sh $dir/install_python.sh
